version: '3'
services:

  gpudb:
    image: kinetica/kinetica-jupyterlab:7.1
    ports:
     - "5601:5601"
     - "8080:8080"
     - "8181:8181"
     - "8082:8082"
     - "8088:8088"
     - "8443:8443"
     - "9002:9002"
     - "9191:9191"
     - "9192:9192"
     - "9193:9193"
     - "9292:9292"
     - "8888:8888"
    container_name: kinetica-jupyterlab-7.x
    environment:
     - FULL_START=1
    privileged: true
    volumes:
      - ../notebooks:/opt/notebooks
      - ./share:/opt/share
    build:
      context: .
      dockerfile: Dockerfile-jupyterlab-7.x
